### ISSUE TITLE
label tag8 does not exist.

### ISSUE THREAD

**Issue by hangupwd** [vesoft-inc/nebula-exchange#111]
你好，我在使用exchange将数据从starrocks迁移到nebula遇到以下问题

![image-20221111173041131](C:\Users\huanghx\AppData\Roaming\Typora\typora-user-images\image-20221111173041131.png)

application.conf为

```
{
  # Spark relation com.vesoft.exchange.common.config
  spark: {
    app: {
      name: Nebula Exchange 2.0
    }

    master:local

    driver: {
      cores: 1
      maxResultSize: 1G
    }

    executor: {
        memory:1G
    }

    cores:{
      max: 16
    }
  }


  # Nebula Graph relation com.vesoft.exchange.common.config
  nebula: {
    address:{
      graph:["xxx:9669"]
      meta:["xxx1:9559"]
    }
    user: xxx
    pswd: xxx
    space: xxx


    # nebula client connection parameters
    connection {
      timeout: 3000
      retry: 3
    }
    
    error: {
      # max number of failures, if the number of failures is bigger than max, then exit the application.
      max: 32
      # failed import job will be recorded in output path
      output: /tmp/errors
    }

    # use google's RateLimiter to limit the requests send to NebulaGraph
    rate: {
      # the stable throughput of RateLimiter
      limit: 1024
      # Acquires a permit from RateLimiter, unit: MILLISECONDS
      # if it can't be obtained within the specified timeout, then give up the request.
      timeout: 1000
    }
  }

  # Processing tags
  # There are tag com.vesoft.exchange.common.config examples for different dataSources.
  
  tags: [

    # MySql
    {
      name: tag8
      type: {
        source: mysql
        sink: client
      }
      host: "xxx"
      port: "9030"
      database: xxx
      table: xxx
      user: xxx
      password:"xxx"
      sentence: "select c_qxbh_fcfe925537604fa4bde0c2aa68a7a361, qxsjwyj_29add450718d44b8bcf27fb662f086a9, c_bs_b6dffaa9b6b147d0a8fd50800288d896, c_hld_a651c2b03c9846668bc6d8c3c36e8042, c_qxdj_f1ecbf4fdb124e2f98d5eff25e4a80ef, c_qxbx_f7fdd980711d4e4e99da81467489a6df, c_qxlx_a2b9afbc695443febadcdd60a6f143f7, c_qxms_f4456e3aa0bf4475ade0c8b2f3b2c31f, c_qxzt_c3e198b836054230892fff177c4bd4d2, c_zydl_cdf591c926564fbc8cac8bd32ec98575, c_zyxl_d9eaf86c143344ada25e31ad57a57897, c_qxly_fe2e01bcb0954347b69b8b687134911b, c_ywcqxclsj_a684714fe03847478964d61a89535dca, c_fxsj_ed665141711f4885bba25d68783dd901, c_fxbz_b4b73a92f6724f05ae064f33d382df45, c_fxr_ed67e99990434094b4ad4afbbbe1ee81, c_tbsj_b468f566a1274befb06a98e9edf2105f, c_tbbz_ec5a192032c44346bbb7cf1540404d1c, c_tbr_e6357b09c9df49e1b1c98f6b49c81448, c_sbsj_f97a16687fe64fbebe139622890f1e75, c_sbbz_af2245c6c33047b8a0ac1a53cc8749e7, c_sbr_b2ac44bae3b947d3a31a030950822f95, c_xqsj_b5d5d565c55b465099c84067e9e59da3, c_xqbz_eb26c79c58da4c56abed5da443cedd99, c_xqr_f2acb55006e94007b8920d69a28b8ccb, c_qxyy_d9021a741f9e42f0b223a1714c96e096, c_qxbw_a94c0cdb9ea84ae08ff75166334e3b5d, c_clcs_e3a8ff9e2c1e4ad9ad8499c0af50c555, c_clqkms_f13ed7ac430b44a09505c787a5565b03, c_yssj_ea33da1f865e41e7bdc79e429fdc3227, c_ysbm_bebf87655b074ac188659e0b172a2cfe, c_ysr_fcaec68d10954a09801e32c1a40ab8d6, c_sbbm_e838098bec344944afbe8beeef1588f8, c_sbyxglbz_ff1413b741314f538e23652b84a4f0c5, c_tyrq_f2f886d2632444748ec845f3a55cee99, c_lcjd_a7a77f5f90c84ed8bb531b244077eca6, c_clr_a453d320d21949f684def001c430868e, c_jsfl_cee20a42023f45e89d90c4b56e17fc61, c_qxyylb_beabf5fe5805497683b1fdbf0ca4d51a, c_sfxybpbj_c83485a68cef4c098bc118533eb56202, c_ylwt_f3c5fcc7612a437f852cfc66395e88e0, c_dgdw_ed1d23ac466e4d9b8279f0c8dff23c45 from collective_31478"
      fields: [c_qxbh_fcfe925537604fa4bde0c2aa68a7a361, qxsjwyj_29add450718d44b8bcf27fb662f086a9, c_bs_b6dffaa9b6b147d0a8fd50800288d896, c_hld_a651c2b03c9846668bc6d8c3c36e8042, c_qxdj_f1ecbf4fdb124e2f98d5eff25e4a80ef, c_qxbx_f7fdd980711d4e4e99da81467489a6df, c_qxlx_a2b9afbc695443febadcdd60a6f143f7, c_qxms_f4456e3aa0bf4475ade0c8b2f3b2c31f, c_qxzt_c3e198b836054230892fff177c4bd4d2, c_zydl_cdf591c926564fbc8cac8bd32ec98575, c_zyxl_d9eaf86c143344ada25e31ad57a57897, c_qxly_fe2e01bcb0954347b69b8b687134911b, c_ywcqxclsj_a684714fe03847478964d61a89535dca, c_fxsj_ed665141711f4885bba25d68783dd901, c_fxbz_b4b73a92f6724f05ae064f33d382df45, c_fxr_ed67e99990434094b4ad4afbbbe1ee81, c_tbsj_b468f566a1274befb06a98e9edf2105f, c_tbbz_ec5a192032c44346bbb7cf1540404d1c, c_tbr_e6357b09c9df49e1b1c98f6b49c81448, c_sbsj_f97a16687fe64fbebe139622890f1e75, c_sbbz_af2245c6c33047b8a0ac1a53cc8749e7, c_sbr_b2ac44bae3b947d3a31a030950822f95, c_xqsj_b5d5d565c55b465099c84067e9e59da3, c_xqbz_eb26c79c58da4c56abed5da443cedd99, c_xqr_f2acb55006e94007b8920d69a28b8ccb, c_qxyy_d9021a741f9e42f0b223a1714c96e096, c_qxbw_a94c0cdb9ea84ae08ff75166334e3b5d, c_clcs_e3a8ff9e2c1e4ad9ad8499c0af50c555, c_clqkms_f13ed7ac430b44a09505c787a5565b03, c_yssj_ea33da1f865e41e7bdc79e429fdc3227, c_ysbm_bebf87655b074ac188659e0b172a2cfe, c_ysr_fcaec68d10954a09801e32c1a40ab8d6, c_sbbm_e838098bec344944afbe8beeef1588f8, c_sbyxglbz_ff1413b741314f538e23652b84a4f0c5, c_tyrq_f2f886d2632444748ec845f3a55cee99, c_lcjd_a7a77f5f90c84ed8bb531b244077eca6, c_clr_a453d320d21949f684def001c430868e, c_jsfl_cee20a42023f45e89d90c4b56e17fc61, c_qxyylb_beabf5fe5805497683b1fdbf0ca4d51a, c_sfxybpbj_c83485a68cef4c098bc118533eb56202, c_ylwt_f3c5fcc7612a437f852cfc66395e88e0, c_dgdw_ed1d23ac466e4d9b8279f0c8dff23c45
      ]
      nebula.fields: [c_qxbh_fcfe925537604fa4bde0c2aa68a7a361, qxsjwyj_29add450718d44b8bcf27fb662f086a9, c_bs_b6dffaa9b6b147d0a8fd50800288d896, c_hld_a651c2b03c9846668bc6d8c3c36e8042, c_qxdj_f1ecbf4fdb124e2f98d5eff25e4a80ef, c_qxbx_f7fdd980711d4e4e99da81467489a6df, c_qxlx_a2b9afbc695443febadcdd60a6f143f7, c_qxms_f4456e3aa0bf4475ade0c8b2f3b2c31f, c_qxzt_c3e198b836054230892fff177c4bd4d2, c_zydl_cdf591c926564fbc8cac8bd32ec98575, c_zyxl_d9eaf86c143344ada25e31ad57a57897, c_qxly_fe2e01bcb0954347b69b8b687134911b, c_ywcqxclsj_a684714fe03847478964d61a89535dca, c_fxsj_ed665141711f4885bba25d68783dd901, c_fxbz_b4b73a92f6724f05ae064f33d382df45, c_fxr_ed67e99990434094b4ad4afbbbe1ee81, c_tbsj_b468f566a1274befb06a98e9edf2105f, c_tbbz_ec5a192032c44346bbb7cf1540404d1c, c_tbr_e6357b09c9df49e1b1c98f6b49c81448, c_sbsj_f97a16687fe64fbebe139622890f1e75, c_sbbz_af2245c6c33047b8a0ac1a53cc8749e7, c_sbr_b2ac44bae3b947d3a31a030950822f95, c_xqsj_b5d5d565c55b465099c84067e9e59da3, c_xqbz_eb26c79c58da4c56abed5da443cedd99, c_xqr_f2acb55006e94007b8920d69a28b8ccb, c_qxyy_d9021a741f9e42f0b223a1714c96e096, c_qxbw_a94c0cdb9ea84ae08ff75166334e3b5d, c_clcs_e3a8ff9e2c1e4ad9ad8499c0af50c555, c_clqkms_f13ed7ac430b44a09505c787a5565b03, c_yssj_ea33da1f865e41e7bdc79e429fdc3227, c_ysbm_bebf87655b074ac188659e0b172a2cfe, c_ysr_fcaec68d10954a09801e32c1a40ab8d6, c_sbbm_e838098bec344944afbe8beeef1588f8, c_sbyxglbz_ff1413b741314f538e23652b84a4f0c5, c_tyrq_f2f886d2632444748ec845f3a55cee99, c_lcjd_a7a77f5f90c84ed8bb531b244077eca6, c_clr_a453d320d21949f684def001c430868e, c_jsfl_cee20a42023f45e89d90c4b56e17fc61, c_qxyylb_beabf5fe5805497683b1fdbf0ca4d51a, c_sfxybpbj_c83485a68cef4c098bc118533eb56202, c_ylwt_f3c5fcc7612a437f852cfc66395e88e0, c_dgdw_ed1d23ac466e4d9b8279f0c8dff23c45]
      vertex: {
        field: com_ontology_entity_025d7bec0eb34213ac4c89b87f15376d
        # policy: "hash"
      }
      batch: 256
      partition: 32
    }
    ]
}

```

麻烦有空看下，thx.

**Comment by hangupwd** [comment]
Exception in thread "main" java.lang.IllegalArgumentException: label tag8 does not exist.
	at com.vesoft.nebula.exchange.utils.NebulaUtils$.getDataSourceFieldType(NebulaUtils.scala:33)
	at com.vesoft.nebula.exchange.processor.VerticesProcessor.process(VerticesProcessor.scala:111)
	at com.vesoft.nebula.exchange.Exchange$$anonfun$main$2.apply(Exchange.scala:150)
	at com.vesoft.nebula.exchange.Exchange$$anonfun$main$2.apply(Exchange.scala:126)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at com.vesoft.nebula.exchange.Exchange$.main(Exchange.scala:126)
	at com.vesoft.nebula.exchange.Exchange.main(Exchange.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:855)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:930)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:939)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
2022-11-11 01:25:44,259 INFO spark.SparkContext: Invoking stop() from shutdown hook

**Comment by Nicole00** [comment]
please check that is there a tag named `tag8` in your NebulaGraph space.

**Comment by QingZ11** [comment]
We have noticed that the issue you created hasn’t been updated for nearly a month, so we have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime. Thanks a lot for your contribution.

**Comment by hangupwd** [comment]
这个是由于没有认真阅读使用文档造成的，已解决，感谢回复
